printWidth: 100
semi: true
singleQuote: true
tabWidth: 2
trailingComma: "all"

overrides:
  - files: "*.njk"
    options:
      parser: "html"
  - files:
      - "*.yml"
      - "*.yaml"
    options:
      singleQuote: false
